# An experimental AppVeyor config to install Strawberry Perl and
# Rakudo Star. Once installed, AppVeyor caches those for use next time.
#
# I specifically don't build Rakudo from GitHub because I want to use
# the "normal people" release.


# AppVeyor environment variables: https://www.appveyor.com/docs/environment-variables/

os: Visual Studio 2015

platform: x64

# clearing the cache: https://github.com/appveyor/ci/issues/985
# change .appveyor_clear_cache.txt to invalidate cache
#
# If the build is successful, AppVeyor caches these files and
# directories for future builds
cache:
    - C:\Strawberry -> .appveyor_clear_cache.txt
    - C:\Rakudo -> .appveyor_clear_cache.txt

branches:
  only:
    - master

# set your own environment variables here.
#
environment:
    MY_VAR: true

install:
  - if not exist "C:\Strawberry" cinst strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - ps: refreshenv
  # multiline must be indented to the same column as the |. Only spaces!
  #
  # Start-Process isn't working. No idea why.
  # https://blogs.msdn.microsoft.com/heaths/2005/11/15/waiting-for-msiexec-exe-to-finish/
  - ps: |
        if ( ! (Test-Path C:\Rakudo) )
        {
          Set-Location -Path "$env:APPVEYOR_BUILD_FOLDER\.."
          Write-Host (Get-Item -Path ".\" -Verbose).FullName
          Start-FileDownload 'http://rakudo.org/downloads/star/rakudo-star-latest-x86_64%20(JIT).msi' -FileName 'rakudo.msi'
          get-filehash -algorithm md5 'rakudo.msi'
          msiexec /i rakudo.msi /quiet /qn /norestart /log rakudo-install.log
        }
  # I'd like this start /wait be be in the above Powershell block but
  # I couldn't make it work.
  #- start /wait msiexec /i rakudo.msi /qn /log rakudo-install.log
  - type rakudo-install.log
  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
  - ps: refreshenv
  - perl6 -v
  # probably want to install zef as a group of steps
  - git clone https://github.com/ugexe/zef %APPVEYOR_BUILD_FOLDER%\..\zef
  - cd %APPVEYOR_BUILD_FOLDER%\..\zef
  - perl6 -Ilib bin/zef install .
  # install the target distribution's dependencies
  - zef --verbose install .
  # change back to the target project's clone folder
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - prove -v -e "perl6 -Ilib" t/

shallow_clone: true

# Other Perl 6 AppVeyor configs
#   https://gist.github.com/ugexe/e95307a3a606df83fdcb
#   https://gist.github.com/MARTIMM/b0cc86cec30dbcabf6e9732a53879dbb/
#   https://github.com/perl6/atom-language-perl6/blob/master/appveyor.yml
#   https://github.com/azawawi/perl6-opencv/blob/master/appveyor.yml
#   https://github.com/ugexe/Perl6-Distribution--Common--Remote/blob/master/.appveyor.yml
#   https://github.com/azawawi/perl6-net-curl/blob/master/appveyor.yml
